# Generated by Django 3.2.13 on 2023-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_movie_id', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.TextField(null=True)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=6, max_digits=12)),
                ('poster_path', models.TextField()),
                ('release_date', models.CharField(max_length=15)),
                ('runtime', models.SmallIntegerField()),
                ('tagline', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.DecimalField(decimal_places=5, max_digits=7)),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
